version: '3'
services:
  resurgence:
    image: registry.gitlab.com/tosk/resurgence/backend:191f7c41
    restart: always
    ports:
      - "443:8080"
    environment:
      spring.datasource.url: jdbc:postgresql://postgres:5432/postgres
      spring.datasource.username: sUpqbm1bH0gHK7QF
      spring.datasource.password: fvTg599LTf366Cw3
      JAVA_TOOL_OPTIONS: "-Xms1G -Xmx1G"
      spring.security.oauth2.client.registration.google.redirect-uri: https://hezaryar.com/{action}/oauth2/code/{registrationId}
      spring.profiles.active: prod,log
      spring.resources.cache.cachecontrol.max-age: "1d"
      server.tomcat.connection-timeout: "10s"
      logging.level.org.zalando.logbook: "trace"
      resurgence.firebase.credential-file: /firebase-adminsdk.json
    volumes:
      - ./firebase-adminsdk.json:/firebase-adminsdk.json
  postgres:
    image: postgres
    restart: always
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: sUpqbm1bH0gHK7QF
      POSTGRES_PASSWORD: fvTg599LTf366Cw3
    volumes:
      - db-data:/var/lib/postgresql/data
  pgbackups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - db-backup-data:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=sUpqbm1bH0gHK7QF
      - POSTGRES_PASSWORD=fvTg599LTf366Cw3
      - SCHEDULE=@midnight
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080

volumes:
  db-data:
  db-backup-data:
