image: maven:3.8.1-openjdk-16

cache:
  paths:
    - .m2/

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2"

stages:
  - build_image

build_image:
  stage: build_image
  variables:
    DOCKER_HOST: "unix:///var/run/docker.sock"
    DOCKER_TLS_VERIFY: 0
    DOCKER_DRIVER: overlay2
  script:
    - mvn spring-boot:build-image
      -Dspring-boot.build-image.imageName=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -DpublishRegistryUrl=https://registry.gitlab.com/tosk/resurgence/backend
      -DpublishRegistryUsername=$CI_REGISTRY_USER
      -DpublishRegistryPassword=$CI_REGISTRY_PASSWORD
      -Dspring-boot.build-image.publish=true
