version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-storage:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  tinode-0:
    image: tinode/tinode:latest
    restart: always
    volumes:
      - ./tinode-development.conf:/etc/tinode/tinode.conf
    ports:
      - "6060:6060"
    environment:
      "STORE_USE_ADAPTER": "mysql"
      "PPROF_URL": "/pprof"
      "EXT_CONFIG": "/etc/tinode/tinode.conf"
      "WAIT_FOR": "mysql:3306"
      "FCM_PUSH_ENABLED": "false"
      "RESET_DB": ${RESET_DB:-false}
      "UPGRADE_DB": ${UPGRADE_DB:-false}
    depends_on:
      - mysql

volumes:
  mysql-storage:
