version: '3.7'

services:
  mysql:
    image: mysql:5.7
    restart: always
    volumes:
      - mysql-storage:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  tinode-0:
    image: tinode/tinode:latest
    restart: always
    volumes:
      - ./tinode.conf:/etc/tinode/tinode.conf
      - ./public.crt:/etc/public.crt
      - ./private.key:/etc/private.key
    ports:
      - "2053:6060"
    environment:
      "STORE_USE_ADAPTER": "mysql"
      "PPROF_URL": "/pprof"
      "EXT_CONFIG": "/etc/tinode/tinode.conf"
      "WAIT_FOR": "mysql:3306"
      "FCM_PUSH_ENABLED": "false"
      "RESET_DB": ${RESET_DB:-false}
      "UPGRADE_DB": ${UPGRADE_DB:-false}
    depends_on:
      - mysql

  exporter-0:
    image: tinode/exporter:latest
    restart: always
    ports:
      - "0.0.0.0:6222:6222"
    links:
      - tinode-0:chat.hezaryar.com
    environment:
      "TINODE_ADDR": "https://chat.hezaryar.com:6060/debug/vars"
      "SERVE_FOR": "prometheus"
      "PROM_NAMESPACE": "tinode"
      "PROM_METRICS_PATH": "/metrics"
      "WAIT_FOR": "tinode-0:6060"
    depends_on:
      - tinode-0

volumes:
  mysql-storage:
