{
 "title": "Chat Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Is running.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tinode_up", "legendFormat": "Up" }
   ]
  },
  {
   "title": "Number of currently active sessions.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tinode_sessions_live_count" }
   ]
  },
  {
   "title": "Number of currently active topics.",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tinode_topics_live_count" }
   ]
  },
  {
   "title": "Number of megabytes of memory allocated and in use.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "tinode_malloced_bytes/(1024*1024)",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Total number of sessions since instance start.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(tinode_sessions_total[5m])",
     "legendFormat": "Sessions"
    }
   ]
  },
  {
   "title": "Total number of topics used during instance lifetime.",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "rate(tinode_topics_total[5m])", "legendFormat": "Sessions" }
   ]
  }
 ]
}