version: '3'

services:
  prometheus:
    image: prom/prometheus
    ports:
    - "0.0.0.0:9090:9090"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml
    - prometheus-storage:/prometheus

  grafana:
    image: grafana/grafana
    ports:
    - "3000:3000"
    volumes:
    - grafana-storage:/var/lib/grafana

volumes:
  prometheus-storage:
  grafana-storage:
